services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3SBS\T3sbootstrap\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  T3SBS\T3sbootstrap\Command\CdnToLocal:
    tags:
      - name: console.command
        command: 't3sbootstrap:cdnToLocal'
        schedulable: true

  T3SBS\T3sbootstrap\Command\CustomScss:
    tags:
      - name: console.command
        command: 't3sbootstrap:customScss'
        schedulable: true

  T3SBS\T3sbootstrap\EventListener\AssetRenderer\IsInline:
    tags:
      - name: event.listener
        identifier: 't3sbootstrap/AssetPreProcessing'

  T3SBS\T3sbootstrap\Backend\EventListener\TCA\TcaCompilation:
    tags:
      - name: event.listener
        identifier: 't3sbootstrap/TcaPostProcessing'

  T3SBS\T3sbootstrap\Backend\EventListener\FlexForm\NewsFlexformEvent:
    tags:
      - name: event.listener
        identifier: 't3sbootstrap/newsFlexParsing'

  T3SBS\T3sbootstrap\Backend\EventListener\FlexForm\FlexformEvent:
    tags:
      - name: event.listener
        identifier: 't3sbootstrap/flexParsing'

  T3SBS\T3sbootstrap\Command\TextpicToTextmedia:
    tags:
      - name: console.command
        command: 't3sbootstrap:textpicToTextmedia'
        schedulable: true

  T3SBS\T3sbootstrap\Command\ImageToTextmedia:
    tags:
      - name: console.command
        command: 't3sbootstrap:imageToTextmedia'
        schedulable: true

  T3SBS\T3sbootstrap\Command\TextToTextmedia:
    tags:
      - name: console.command
        command: 't3sbootstrap:textToTextmedia'
        schedulable: true
